---
- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: reload sysctl
  command: sysctl --system

- name: run rkhunter
  command: rkhunter --propupd
  ignore_errors: yes
  register: rkhunter_result
  changed_when: "'File updated' in rkhunter_result.stdout"

- name: reload apparmor
  service:
    name: apparmor
    state: reloaded 