---
- name: Include SSH setup tasks
  include_tasks: ssh_setup.yml

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
  vars:
    common_packages:
      - curl
      - wget
      - vim
      - htop
      - net-tools
      - dnsutils
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - logrotate
      - rsyslog
      - fail2ban
      - ufw
      - auditd
      - libpam-pwquality
      - openssh-server
      - python3
      - python3-pip
      - python3-apt

- name: Create oo-acs user
  user:
    name: oo-acs
    shell: /bin/bash
    create_home: yes
    home: /home/oo-acs
    groups: sudo
    append: yes
    state: present

- name: Configure system-wide security limits
  copy:
    src: limits.conf
    dest: /etc/security/limits.d/90-oo-acs.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure sysctl security settings
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/90-oo-acs.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl settings
  command: sysctl -p /etc/sysctl.d/90-oo-acs.conf

- name: Configure SSH server
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: Configure UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443
  notify: restart ufw

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
  notify: restart ufw 