---
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Copy SSH private key
  copy:
    src: "/Users/unixthat/.ssh/linodeKey"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  no_log: true

- name: Generate SSH public key from private key
  shell: "ssh-keygen -y -f {{ ansible_env.HOME }}/.ssh/id_ed25519 > {{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
  no_log: true

- name: Add SSH key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '/Users/unixthat/.ssh/linodeKey.pub') }}"
    state: present
  no_log: true

- name: Ensure SSH config exists
  copy:
    content: |
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        IdentityFile /Users/unixthat/.ssh/id_ed25519
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0600' 