name: CITS3007-DevEnvironment
description: Sets up the CITS3007 secure coding development environment
schemaVersion: 1.0
phases:
  - name: build
    steps:
      - name: InstallPackages
        action: ExecuteBash
        inputs:
          commands:
            - apt-get update
            - apt-get install -y software-properties-common
            - add-apt-repository universe
            - apt-get update
            - apt-get install -y build-essential cmake
            - apt-get install -y clang llvm
            - apt-get install -y afl
            - apt-get install -y valgrind
            - apt-get install -y gdb
            - apt-get install -y splint
            - apt-get install -y python3 python3-pip
            - apt-get install -y gcov lcov 