name: CITS3007-DevEnvironment
description: Development environment for CITS3007 with all required packages and configurations
schemaVersion: 1.0
phases:
  - name: build
    steps:
      - name: UpdateSystem
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/usr/bin/env bash
              
              # CITS3007 Development Environment Component
              # Version: 1.0.0
              # Description: Sets up the CITS3007 secure coding development environment
              # Following the golden rule: NEVER GUESS A COMMAND. IF UNSURE, CHECK THE DOCS.
              
              # should be run as root
              set -x
              set -euo pipefail
              
              # Update package lists
              apt-get update
              
              # should already have: wget, curl
              
              # Install basic apps (from provision-01.sh)
              # These are the core utilities needed for the environment
              DEBIAN_FRONTEND=noninteractive \
                apt-get install --no-install-recommends -y \
                  apt-transport-https     \
                  aptitude                \
                  bash                    \
                  bash-completion         \
                  bzip2                   \
                  ca-certificates         \
                  command-not-found       \
                  expect                  \
                  file                    \
                  fakeroot                \
                  gpg                     \
                  jq                      \
                  less                    \
                  lsof                    \
                  lynx                    \
                  netcat-openbsd          \
                  procps                  \
                  pv                      \
                  openssh-client          \
                  screen                  \
                  sudo                    \
                  time
              
              # Install extra utilities (from provision-01.sh)
              # Additional tools for system management and file operations
              DEBIAN_FRONTEND=noninteractive \
                apt-get install --no-install-recommends -y \
                  binutils                \
                  bsdmainutils            \
                  coreutils               \
                  diffutils               \
                  findutils               \
                  moreutils               \
                  patchutils              \
                  sharutils
      
      - name: InstallDevTools
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/usr/bin/env bash
              
              # CITS3007 Development Environment Component
              # Version: 1.0.0
              # Description: Installs development tools for CITS3007
              
              # should be run as root
              set -x
              set -euo pipefail
              
              # Install development tools (from provision-02.sh)
              # These are the tools needed for secure coding development
              DEBIAN_FRONTEND=noninteractive \
                apt-get install --no-install-recommends -y \
                  afl++-clang             \
                  build-essential         \
                  clang                   \
                  clang-format            \
                  clang-tidy              \
                  clang-tools             \
                  g++-multilib            \
                  gdb                     \
                  git                     \
                  gpg                     \
                  indent                  \
                  libtool                 \
                  llvm-10-dev             \
                  pkg-config              \
                  splint                  \
                  universal-ctags         \
                  valgrind                \
                  xxd                     \
                  zzuf
              
              # Install documentation packages (from provision-02.sh)
              # These provide man pages and documentation for the installed tools
              DEBIAN_FRONTEND=noninteractive \
                apt-get install --no-install-recommends -y \
                  man-db                  \
                  manpages                \
                  manpages-dev            \
                  manpages-posix          \
                  manpages-posix-dev
      
      - name: ConfigureLocale
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/usr/bin/env bash
              
              # CITS3007 Development Environment Component
              # Version: 1.0.0
              # Description: Configures locale settings for en_AU.UTF-8
              
              # should be run as root
              set -x
              set -euo pipefail
              
              # Configure locale for en_AU.UTF-8
              # This prevents locale warnings and ensures consistent environment
              DEBIAN_FRONTEND=noninteractive apt-get install -y locales
              sed -i 's/# en_AU.UTF-8 UTF-8/en_AU.UTF-8 UTF-8/' /etc/locale.gen
              locale-gen en_AU.UTF-8
              update-locale LANG=en_AU.UTF-8 LC_ALL=en_AU.UTF-8
              
              # Set environment variables for current session and future sessions
              echo "export LANG=en_AU.UTF-8" >> /etc/environment
              echo "export LC_ALL=en_AU.UTF-8" >> /etc/environment
      
      - name: ConfigureNetwork
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/usr/bin/env bash
              
              # CITS3007 Development Environment Component
              # Version: 1.0.0
              # Description: Configures network settings
              
              # should be run as root
              set -x
              set -euo pipefail
              
              # Configure network settings (from provision-02.sh)
              # Set up netplan for DHCP on eth0
              echo "Create netplan config for eth0"
              mkdir -p /etc/netplan
              cat <<EOF >/etc/netplan/01-netcfg.yaml
              network:
                version: 2
                ethernets:
                  eth0:
                    dhcp4: true
              EOF
              
              # Update GRUB configuration
              update-grub
              
              # Configure systemd-resolved
              # Comment out DNS and Cache lines to prevent DNS issues
              echo "disable pointless resolved.conf lines"
              sed -i 's/^DNS/#&/; s/^Cache/#&/;' /etc/systemd/resolved.conf
              
              # Restart systemd-resolved to apply changes
              systemctl daemon-reload
              systemctl restart systemd-resolved
      
      - name: Cleanup
        action: ExecuteBash
        inputs:
          commands:
            - |
              #!/usr/bin/env bash
              
              # CITS3007 Development Environment Component
              # Version: 1.0.0
              # Description: Performs cleanup operations
              
              # should be run as root
              set -x
              set -euo pipefail
              
              # Clean up package lists and cache to reduce image size
              apt-get clean
              rm -rf /var/lib/apt/lists/*
              
              # Verify installation
              echo "Verifying installation..."
              dpkg -l | grep -E "afl\+\+-clang|build-essential|clang|llvm-10-dev"
              
              # Print locale information
              echo "Locale information:"
              locale
              
              # Print network configuration
              echo "Network configuration:"
              cat /etc/netplan/01-netcfg.yaml
              
              echo "CITS3007 Development Environment setup complete!" 