---
- name: Provision Linode Staging Environment
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../group_vars/all/vault.yml # Explicitly include vault file
  vars:
    linode_instance_label: oo-acs-staging
    linode_instance_type: g6-standard-1 # 2GB Standard
    linode_instance_region: ap-southeast # Sydney, AU
    linode_instance_image: linode/ubuntu20.04
    linode_instance_tags:
      - staging
      - oo-acs
    linode_ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHkzQ7fAkTmclUvsWBxKBmNrBcipmLEfk0+nQD6X/HDH unixthat@Stephens-MacBook-Air.local"
    linode_firewall_name: fw-staging-basic

  tasks:
    - name: Ensure Linode API token is set
      fail:
        msg: "LINODE_TOKEN environment variable is not set. Please set it before running this playbook."
      when: lookup('env', 'LINODE_TOKEN') | length == 0
      run_once: yes

    - name: Delete existing Staging instance (if any) for a clean build
      linode.cloud.instance:
        label: "{{ linode_instance_label }}"
        state: absent
      delegate_to: localhost
      ignore_errors: yes # Don't fail if the instance doesn't exist

    - name: Create Linode Staging instance
      linode.cloud.instance: # Use FQCN
        label: "{{ linode_instance_label }}"
        type: "{{ linode_instance_type }}"
        region: "{{ linode_instance_region }}"
        image: "{{ linode_instance_image }}"
        root_pass: "{{ vault_linode_root_password }}" # Reverted back to Vault variable
        authorized_keys:
          - "{{ linode_ssh_pub_key }}"
        tags: "{{ linode_instance_tags }}"
        state: present
      register: staging_instance # Use staging_instance variable
      delegate_to: localhost # Explicitly run on control node

    - name: Add new instance to inventory group
      add_host:
        name: "{{ staging_instance.instance.ipv4[0] }}" # Use the first public IPv4
        groups: linode_staging_instances # Add to staging group
        ansible_user: root # Initially connect as root
        ansible_ssh_private_key_file: ~/.ssh/linodeKey
      when: staging_instance.changed

    - name: Create Linode Firewall for Staging instance
      linode.cloud.firewall: # Use FQCN
        label: "{{ linode_firewall_name }}"
        rules: # Dictionary containing policies and rule lists
          inbound_policy: DROP  # Default policy for inbound
          outbound_policy: ACCEPT # Default policy for outbound
          inbound: # List of inbound rules
            - label: allow-ssh
              # No 'direction' needed here
              protocol: TCP
              ports: '22'
              addresses:
                ipv4: ['0.0.0.0/0']
                ipv6: ['::/0']
              action: ACCEPT
        devices: # List of dictionaries
          - id: "{{ staging_instance.instance.id | int }}"
            # type: linode # Optional, defaults to linode
        state: present
      delegate_to: localhost # Explicitly run on control node
      when: staging_instance.changed # Only create/update firewall if instance was created/changed

    - name: Display Staging Instance IP
      debug:
        msg: "Staging instance created with IP: {{ staging_instance.instance.ipv4[0] }}"
      when: staging_instance.changed 