---
- name: Configure Staging Environment
  hosts: staging
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - build-essential
          - git
          - python3-pip
          - python3-venv
          - libssl-dev
          - pkg-config
          - nginx
        state: present

    - name: Install Python packages
      pip:
        name:
          - pytest
          - coverage
        state: present

    - name: Create oo-acs group
      group:
        name: oo-acs
        state: present

    - name: Create oo-acs user
      user:
        name: oo-acs
        group: oo-acs
        shell: /bin/bash
        create_home: yes
        home: /home/oo-acs
        state: present

  roles:
    - common
    - security

  tasks:
    - name: Create application directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: oo-acs
        group: oo-acs
      loop:
        - /opt/oo-acs
        - /opt/oo-acs/logs
        - /opt/oo-acs/data

  vars:
    env_name: staging
    instance_type: g6-standard-1
    linode_instance_region: ap-southeast
    linode_instance_image: linode/ubuntu20.04

  post_tasks:
    - name: Ensure all services are started
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - ufw
        - fail2ban
        - ssh
        - nginx

    - name: Verify installed packages
      command: "{{ item }}"
      register: package_versions
      changed_when: false
      loop:
        - python3 --version
        - nginx -v

    - name: Display package versions
      debug:
        var: package_versions.results

    - name: Final security check
      command: ufw status
      register: ufw_status
      changed_when: false

    - name: Display security status
      debug:
        var: ufw_status.stdout_lines 