---
- name: Configure Testing Environment
  hosts: testing-server
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - build-essential
          - cmake
          - gcc
          - g++
          - make
          - valgrind
          - gdb
          - git
          - doxygen
          - graphviz
          - clang
          - clang-tools
          - libssl-dev
          - libsodium-dev
          - pkg-config
          - python3-pip
          - python3-venv
          - python3-dev
          - afl++
          - lcov
          - cppcheck
        state: present

    - name: Install Python development tools
      pip:
        name:
          - pre-commit
          - black
          - pylint
          - pytest
          - coverage
        state: present

    - name: Create oo-acs group
      group:
        name: oo-acs
        state: present

    - name: Create oo-acs user
      user:
        name: oo-acs
        group: oo-acs
        shell: /bin/bash
        create_home: yes
        home: /home/oo-acs
        state: present

  roles:
    - common
    - security
    - build_tools

  tasks:
    - name: Clone Unity testing framework
      git:
        repo: https://github.com/ThrowTheSwitch/Unity.git
        dest: /opt/unity
        version: master

    - name: Create Unity symlink
      file:
        src: /opt/unity
        dest: /usr/local/include/unity
        state: link

    - name: Create development directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: oo-acs
        group: oo-acs
      loop:
        - /opt/oo-acs
        - /opt/oo-acs/build
        - /opt/oo-acs/tests
        - /opt/oo-acs/docs

    - name: Set up environment variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        create: yes
      loop:
        - 'CFLAGS="-Wall -Wextra -Werror -g -O0 -fprofile-arcs -ftest-coverage"'
        - 'CXXFLAGS="-Wall -Wextra -Werror -g -O0 -fprofile-arcs -ftest-coverage"'
        - 'LDFLAGS="--coverage"'
        - 'UNITY_PATH=/usr/local/include/unity'

  vars:
    env_name: testing
    instance_type: g6-nanode-1
    linode_instance_region: ap-southeast
    linode_instance_image: linode/ubuntu20.04

  post_tasks:
    - name: Ensure all services are started
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - ufw
        - fail2ban
        - ssh

    - name: Verify development tools
      command: "{{ item }}"
      register: tool_versions
      changed_when: false
      loop:
        - gcc --version
        - g++ --version
        - cmake --version
        - python3 --version
        - valgrind --version
        - gdb --version
        - clang --version

    - name: Display tool versions
      debug:
        var: tool_versions.results

    - name: Final security check
      command: ufw status
      register: ufw_status
      changed_when: false

    - name: Display security status
      debug:
        var: ufw_status.stdout_lines 