name: Staging Environment CI/CD

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd tests
          python -m pytest --cov=../src --cov-report=xml
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./tests/coverage.xml
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}
          if_key_exists: fail
          
      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no oo-acs-deploy@${{ secrets.STAGING_HOST }} "cd /var/www/oo-acs && \
            sudo git fetch origin && \
            sudo git checkout staging && \
            sudo git pull origin staging && \
            sudo make clean && \
            sudo make && \
            sudo make test && \
            sudo make install && \
            sudo systemctl restart oo-acs && \
            sudo apt update && \
            sudo apt upgrade -y"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_STAGING_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to Staging Server
        run: |
          ssh -i ~/.ssh/id_ed25519 oo-acs-deploy@${{ secrets.STAGING_HOST }} << 'EOF'
            cd /opt/oo-acs
            git pull origin staging
            sudo make test
            if [ $? -eq 0 ]; then
              sudo make install
              sudo make integration-test
              if [ $? -eq 0 ]; then
                sudo systemctl restart oo-acs
              fi
            fi
          EOF 