---
# Security packages to install
security_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - acl
  - auditd
  - rkhunter
  - libpam-pwquality

# UFW allowed ports (base configuration)
ufw_allowed_ports:
  - 22    # SSH
  - 80    # HTTP
  - 443   # HTTPS

# Sysctl security settings
sysctl_settings:
  # IPv4 settings
  'net.ipv4.conf.all.accept_redirects': 0
  'net.ipv4.conf.all.accept_source_route': 0
  'net.ipv4.conf.all.log_martians': 1
  'net.ipv4.conf.all.rp_filter': 1
  'net.ipv4.conf.all.secure_redirects': 0
  'net.ipv4.conf.default.accept_redirects': 0
  'net.ipv4.conf.default.accept_source_route': 0
  'net.ipv4.icmp_echo_ignore_broadcasts': 1
  'net.ipv4.tcp_syncookies': 1
  # IPv6 settings
  'net.ipv6.conf.all.accept_redirects': 0
  'net.ipv6.conf.default.accept_redirects': 0
  # System settings
  'kernel.core_uses_pid': 1
  'kernel.dmesg_restrict': 1
  'kernel.kptr_restrict': 2
  'kernel.sysrq': 0
  'fs.suid_dumpable': 0

# Security limits
security_limits:
  - domain: '*'
    type: soft
    item: nofile
    value: 65535
  - domain: '*'
    type: hard
    item: nofile
    value: 65535
  - domain: '*'
    type: soft
    item: nproc
    value: 4096
  - domain: '*'
    type: hard
    item: nproc
    value: 4096

# SSH Configuration
ssh_config:
  port: 22
  permit_root_login: 'no'
  password_authentication: 'no'
  x11_forwarding: 'no'
  max_auth_tries: 3
  pubkey_authentication: 'yes'
  authorized_keys_file: '.ssh/authorized_keys'
  protocol_version: 2
  ignore_rhosts: 'yes'
  host_based_auth: 'no'
  permit_empty_passwords: 'no'
  challenge_response_auth: 'no'
  kerberos_authentication: 'no'
  gssapi_authentication: 'no'
  use_pam: 'yes'
  allow_agent_forwarding: 'no'
  allow_tcp_forwarding: 'no'
  print_motd: 'no'
  print_lastlog: 'yes'
  tcp_keepalive: 'yes'
  max_sessions: 4
  client_alive_interval: 300
  client_alive_count_max: 2
  login_grace_time: 60
  banner: '/etc/issue.net' 